# Generated by Django 4.1 on 2022-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='razorpay_gateway_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_id', models.CharField(max_length=50)),
                ('razorpay_SECRET', models.CharField(max_length=50)),
                ('call_back_url', models.URLField()),
            ],
        ),
    ]
