# Generated by Django 4.1 on 2022-08-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.TextField(max_length=32)),
                ('img', models.ImageField(upload_to='upload/img')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Hoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('price', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.type')),
                ('hoarding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.city')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.image')),
            ],
        ),
    ]
