# Generated by Django 4.1 on 2022-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_hoarding_city_alter_hoarding_hoarding_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoarding',
            name='images',
        ),
        migrations.AddField(
            model_name='hoarding',
            name='images',
            field=models.ManyToManyField(to='Home.image'),
        ),
    ]
