# Generated by Django 4.1 on 2022-08-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_image_img_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='hoarding',
            name='images',
            field=models.ManyToManyField(through='Home.Image2', to='Home.image'),
        ),
        migrations.AddField(
            model_name='image2',
            name='hoarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.hoarding'),
        ),
        migrations.AddField(
            model_name='image2',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.image'),
        ),
    ]
