# Generated by Django 4.1 on 2022-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_image2_alter_hoarding_images_image2_hoarding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoarding',
            name='images',
            field=models.ManyToManyField(through='Home.Image2', to='Home.image'),
        ),
    ]
