# Generated by Django 4.1 on 2022-08-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('Company_logo', models.ImageField(upload_to='upload/logo')),
                ('Company_description', models.TextField(max_length=400)),
                ('Company_phone_number', models.CharField(max_length=12)),
                ('Company_whatsapp_number', models.CharField(max_length=12)),
                ('Company_email', models.EmailField(max_length=254)),
                ('Company_facebook_link', models.URLField(max_length=50)),
                ('Company_instagram_link', models.URLField(max_length=50)),
                ('Company_address', models.TextField(max_length=500)),
                ('Company_latitude', models.CharField(max_length=10)),
                ('Company_longitude', models.CharField(max_length=10)),
            ],
        ),
    ]
